apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-yield
  namespace: crop-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crop-yield
  template:
    metadata:
      labels:
        app: crop-yield
    spec:
      containers:
        - name: app
          image: indian-crop-yield:prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 10
