apiVersion: v1
kind: Service
metadata:
  name: crop-yield-svc
  namespace: crop-prod
spec:
  type: NodePort
  selector:
    app: crop-yield
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30080
